version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - prometheus
    networks:
      - monitor-net
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=testenest
    networks:
      - monitor-net
  websocket-client:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: ['node', 'test-socket.mjs']
    depends_on:
      - app
    networks:
      - monitor-net
networks:
  monitor-net:
    driver: bridge
