version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - prometheus
    networks:
      - monitor-net
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    networks:
      - monitor-net
networks:
  monitor-net:
    driver: bridge
